MAX_ANALYSIS_POSTS_AND_REELS = 50
MAX_ANALYSIS_FOLLOWERS_AND_FOLLOWS = 10000
MAX_ANALYSIS_LIKES_AND_COMMENTS = 1000000

MAX_OUTPUT_TOP_LIKERS_COUNT = 5
MAX_OUTPUT_TOP_COMMENTATORS_COUNT = 5
MAX_OUTPUT_TOP_ACTIVITIES_COUNT = 10
MAX_OUTPUT_POSTS_COUNT = 8
MAX_OUTPUT_POST_WITH_ACTIVITY = 4
